version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./apps/frontend
    volumes:
      - ./apps/frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./.env
    restart: always
    command: "yarn dev"

  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres:alpine
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres_db

  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - CACHE_URL=redis://redis:6379/0
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    container_name: celery
    command: 'celery -A integraflow worker --loglevel=info'
    depends_on:
      - redis
      - backend
