version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - ./data/redis:/data

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres_db

  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
      - /backend/.venv
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - CACHE_URL=redis://redis:6379/0
    command: bash -c "poetry run python manage.py migrate --noinput && poetry run python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
      - /backend/.venv
    env_file:
      - ./.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    container_name: celery
    command: bash -c "poetry run celery -A integraflow worker --loglevel=info"
    depends_on:
      - redis
      - backend
