version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis

  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./.env
    ports:
      - 8000:8000
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CACHE_URL=redis://redis:6379/0
    restart: always
