version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres_db
    ports:
      - 5432:5432

  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./.env
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres.ugojraljnvusodkofopv:m9BBOv64a9rtvA2g@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CACHE_URL=redis://redis:6379/0
    restart: always
    depends_on:
      - db
