
app = "your-app-name"
primary_region = "iad" # Change this to your preferred Fly.io region

[build]
  dockerfile = "backend/Dockerfile"
  build-target = "backend"

[deploy]
  strategy = "rolling"

[experimental]
  cmd = ["docker", "compose", "-f", "docker-compose-deploy.yml", "up"]

[processes]
  app = "docker compose -f docker-compose-deploy.yml up"
