name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set environment variables
        run:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Build backend server
        run: docker compose -f ./docker-compose.yml build

      - name: Start Backend Server
        run: docker compose -f ./docker-compose.yml up -d

      - name: Navigate to Frontend Directory
        working-directory: apps/frontend
        run: pwd

      - name: Install dependencies
        working-directory: apps/frontend
        run: npm install -g yarn && yarn

      - name: Install Playwright Browsers
        working-directory: apps/frontend
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        working-directory: apps/frontend
        run: yarn playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/frontend/playwright-report/
          retention-days: 30
